name: minesweeper
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #---------- flutter.dev plugin
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  go_router: ^15.1.2

  #---------- dart.dev plugin
  # core
  path: ^1.9.1
  collection: ^1.19.1
  # i18n
  intl: ^0.20.2
  # async
  async: ^2.13.0

  #---------- google.dev plugin
  json_annotation: ^4.9.0
  tuple: ^2.0.2

  #---------- flutter community
  share_plus: ^11.0.0

  #---------- third party plugin
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.33
  sqlite3: ^2.7.6

  uuid: ^4.5.1
  permission_handler: ^12.0.0+1
  logger: ^2.5.0
  bot_toast: ^4.1.3
  app_links: ^6.4.0
  # state management
  get: ^4.7.2
  flex_color_scheme: ^8.2.0
  # audio
  just_audio: ^0.10.4
  duration: ^4.0.3

  universal_platform: ^1.1.0

  # desktop
  tray_manager: ^0.5.0
  window_manager: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1
  pigeon: ^25.3.2
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/music/
